### ISSUE TITLE
哈哈，好家伙，隐藏可以， 点Reset 不能恢复成之前的样子

### ISSUE THREAD

**Issue by markyun** [cunzaizhuyi/up-mode-extension#2]
不能恢复啊，老哥。

<img width="439" alt="image" src="https://github.com/user-attachments/assets/62176e27-2bf0-44f3-ae8e-e91d690f34bf">

**Comment by cunzaizhuyi** [comment]
我这Chrome装了 30 多个插件，都可以恢复。 
但不排除确实有兼容问题，目前不知道啥情况了，等一个复现视频吧

**Comment by VincentYoungAtGitHub** [comment]
我这边有相同现象。
安装版本为商店版0.0.1： https://chromewebstore.google.com/detail/up-mode/maiiinianakmklepgbpffmgmhpnoniem?hl=zh-CN&utm_source=ext_sidebar

操作系统：MacOS 14.6.1 (23G93)
浏览器版本：版本 128.0.6613.138（正式版本） (arm64)

**Comment by cunzaizhuyi** [comment]
已修复，下载最新的zip试试。   应用商店正在审核中
