### ISSUE TITLE
期待可以隐藏书签栏和 tab

### ISSUE THREAD

**Issue by sangshuduo** [cunzaizhuyi/up-mode-extension#3]

**Comment by cunzaizhuyi** [comment]
隐藏书签栏我试过了，实现不了，浏览器安全策略限制。
隐藏TAB，可以看看~

**Comment by DeltaView** [comment]
well, you can hide bookmarks bar manually. Use keyboard command <kbd>CTRL</kbd> + <kbd>Shift</kbd> + <kbd>B</kbd> on Windows to toggle it. You can also right click on the bookmarks bar and unselect the corresponding option.
